/**
 * This file contains configuration parameters for voxl-cpu-monitor.
 *
 *
 * en_auto_pitmode:   enable cpu-monitor to put CPU in a lower power state
 *                      when Autopilot is disarmed
 *
 * normal_governor:   cpu governor to use normally, default: auto
 *                      options are: auto, cool, performance, powersave, conservative
 *
 * pitmode_governor:  cpu governor to use when in pitmode, default: cool
 *                    options are: auto, cool, performance, powersave, conservative
 *
 */
{
	"en_auto_pitmode":	true,
	"normal_governor":	"auto",
	"pitmode_governor":	"auto"
}
